//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scLInq.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_scLInqEntities : DbContext
    {
        public db_scLInqEntities()
            : base("name=db_scLInqEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbDepartment> tbDepartments { get; set; }
        public virtual DbSet<tbFAQ> tbFAQs { get; set; }
        public virtual DbSet<tbFAQDocument> tbFAQDocuments { get; set; }
        public virtual DbSet<tbJobFunction> tbJobFunctions { get; set; }
        public virtual DbSet<tbLocation> tbLocations { get; set; }
        public virtual DbSet<tbUser> tbUsers { get; set; }
    }
}
