//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scLInq.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbJobFunction
    {
        public int JobFunctionId { get; set; }
        public string JobFunctionName { get; set; }
        public Nullable<int> DeptId { get; set; }
    
        public virtual tbDepartment tbDepartment { get; set; }
    }
}
